== Scope

This optional OGC CDB Extension defines the behavior and requirements for encoding vector data in a GeoPackage container for use in a CDB data store. The requirements and related guidance are grounded in the existing CDB Core requirements and the GeoPackage core requirements for vector data. As such, any GeoPackage that is to be referenced/used in a CDB data store must be 1.) compliant with the CDB core requirements for vector data and 2.) compliant with the GeoPackage core requirements for encoding vector data. Please note that some of the core GeoPackage requirements are profiled in order to be consistent with the CDB core requirements as specified in https://portal.opengeospatial.org/files/15-113r5[Volume 1: OGC CDB Core Standard: Model and Physical Data Store Structure]. Further, there are associated normative additions to the CDB Core to accommodate not just the use of GeoPackages but also other vector storage encodings/containers.

Before reading this documentd, please remember that the idea is to restrict the encoding of a dataset to a single vector format per CDB Version. Since a “CDB” is made of one or more “Versions” (as specified by Configuration.xml), and that each CDB Version can have a different encoding for a given dataset, the result is that a “CDB” data store pmay have multiple encodings for the same dataset. This means that if using GeoPackage containers is desired, then a Version must be created that will only contain GeoPackages of the vector data and not include any Shapefiles.

For ease of editing and review, the CDB Standard has been separated into 15 document Volumes and a schema repository. +


* Volume 0: OGC CDB Companion Primer for the CDB standard (Best Practice).
* Volume 1: OGC CDB Core Standard: Model and Physical Data Store Structure. The main body (core) of the CDB standard (Normative).
* Volume 2: OGC CDB Core Model and Physical Structure Annexes (Best Practice).
* Volume 3: OGC CDB Terms and Definitions (Normative).
* Volume 4: OGC CDB Rules for Encoding CDB Vector Data using Shapefiles (Best Practice).
* Volume 5: OGC CDB Radar Cross Section (RCS) Models (Best Practice).
* Volume 6: OGC CDB Rules for Encoding CDB Models using OpenFlight (Best Practice).
* Volume 7: OGC CDB Data Model Guidance (Best Practice).
* Volume 8: OGC CDB Spatial Reference System Guidance (Best Practice).
* Volume 9: OGC CDB Schema Package: http://schemas.opengis.net/cdb/ provides the normative schemas for key features types required in the synthetic modeling environment. Essentially, these schemas are designed to enable semantic interoperability within the simulation context (Normative).
* Volume 10: OGC CDB Implementation Guidance (Best Practice).
* Volume 11: OGC CDB Core Standard Conceptual Model (Normative).
* Volume 12: OGC CDB Navaids Attribution and Navaids Attribution Enumeration Values (Best Practice).
* Volume 13: OGC CDB Rules for Encoding CDB Vector Data using GeoPackage (Normative, Optional Extension).
* Volume 14: OGC CDB Guidance on Conversion of CDB Shapefiles into CDB GeoPackages (Best Practice).
* OGC CDB Optional Multi-Spectral Imagery Extension (Normative).
