== Requirements for Using GeoPackages in a CDB Data Store
This section defines the mandatory requirements for having GeoPackage containers in a structured CDB data store. Many of the requirements are _by reference_ to specific requirements in both the GeoPackage and CDB standards. The referenced requirements are known as _dependent_ requirements. For example, the GeoPackage standrds specifies that any valid GeoPackage shall have a file extension of .gpkg. The optional CDB GeoPackage extension specifies the same requirement.

=== Requirement that one and only vector format can be in a CDB version
The following requirement clearly states that any given version has only one allowed vector format. Currently, the two supported formats are the traditional Shapefiles and now GeoPackages. However, a CDB data store may have multiple versions. Therefore, the Shapefile format could be used in one version and GeoPackages used in another version.

include::requirements/REQ001.adoc[]

=== GeoPackage Requirements
The following requirement class captures all of the GeoPackage requirements that need to be implemented in order to be a fully compliant GeoPackage for use in a CDB data store. Please note that GeoPackage Requirement xx on Coordiante Reference Systems has been profiled to be consistent with the mandatory requirements in the CDB standard.

include::requirements/REQ001.adoc[]

[cols=",,,",options="header",]
|===
|*Value* | *GeoPackage geometry type* |*Shapefile Vector type* |*Fields*
|0 ||Null shape |None
|1 |Point | Point | X, Y
|3 |Linestring | Polyline |MBR, Number of parts, Number of points, Parts, Points
|5 |Polygon |Polygon |MBR, Number of parts, Number of points, Parts, Points
|8 |MultiPoint |MultiPoint |MBR, Number of points, Points
|11 |Point | PointZ a| X, Y, Z _Optional_: M
|13 | Linestring | PolylineZ a| _Mandatory_: MBR, Number of parts, Number of points, Parts, Points, Z range, Z array _Optional_: M range, M array
|15 |Polygon | PolygonZ a| _Mandatory_: MBR, Number of parts, Number of points, Parts, Points, Z range, Z array _Optional_: M range, M array
|18 | Multipoint | MultiPointZ a| _Mandatory_: MBR, Number of points, Points, Z range, Z array _Optional_: M range, M array
|21 |Point | PointM |X, Y, M
|23 | Linestring | PolylineM a| _Mandatory_: MBR, Number of parts, Number of points, Parts, Points _Optional_: M range, M array
|25 | Polygon | PolygonM a| _Mandatory_: MBR, Number of parts, Number of points, Parts, Points _Optional_: M range, M array
|28 |MultiPoint | MultiPointM a| _Mandatory_: MBR, Number of points, Points _Optional Fields_: M range, M array
|31 | Surface | MultiPatch a| _Mandatory_: MBR, Number of parts, Number of points, Parts, Part types, Points, Z range, Z array _Optional_: M range, M array

|===

=== Requirement CDB Core
The following requirement defines how vector data in a GeoPackage is to be structured based on requirements specified in the CDB Core document.

include::requirements/REQ003.adoc[]

Use the following table for Requirements Classes.

include::requirements/requirements_class.adoc[]

==== Requirement 3
Paragraph - intro text for the requirement.

include::requirements/REQ003.adoc[]
