== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r8], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

=== *coordinate reference system*
coordinate system that is related to the real world by a datum [ISO 19111]

=== *coordinate system*
set of mathematical rules for specifying how coordinates are to be assigned to points [ISO 19111]

=== *dataset*
collection of data, published or curated by a single agent, and available for access or download in one or more formats <<DCAT>>

NOTE: The use of 'collection' in the definition from <<DCAT>> is broader than
the use of the term collection in this standard. See the definition of feature collection.

=== *feature*
abstraction of real world phenomena [ISO 19101-1:2014]

NOTE: If you are unfamiliar with the term 'feature', the explanations on link:https://www.w3.org/TR/sdw-bp/#spatial-things-features-and-geometry[Spatial Things, Features and Geometry] in the <<SDWBP,W3C/OGC Spatial Data on the Web Best Practice document>> provide more detail.

=== *feature collection; collection*
a set of *features* from a *dataset*

NOTE: In this standard, 'collection' is used as a synonym for 'feature
collection'. This is done to make this document easier to understand for those that are not geo-experts.

=== *GeoPackage file*

a platform-independent SQLite database file that contains GeoPackage data and metadata tables with specified definitions, integrity assertions, format limitations and content constraints.

=== *tile*
a geometric shape with known properties that is the result of the tiling (tessellation) of a plane. A tile consists of a single connected "piece" without "holes" or "lines" (topological disc).

=== *Valid GeoPackage*

A GeoPackage that contains features per clause Features and/or tiles per clause Tiles and row(s) in the gpkg_contents table with data_type column values of "features" and/or "tiles" describing the user data tables.


== Abbreviations
