== Conformance

Needs work once the normative clauses are specified.

This Standard defines requirements classes, requirements and conformance classes applicable to the implementation of the CDB 2.0 GeoPackage Application Profile.

The standardization targets of all conformance classes are "GeoPackages in CDB 2.0 Datastore".

The main requirements class is:

    CDB-2-GeoPackage-AP. <<Add link to Annex A later>>

The CDB-2-GeoPackage-AP requirements class specifies requirements that _SHALL_l be implemented for all GeoPackages that are to be stored in a CDB datastore. The requirements defined in the 

Conformance with this standard shall be checked using all the relevant tests specified in Annex A (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

In order to conform to this OGC® interface standard, a software implementation shall choose to implement the conformance levels specified in Annex A (normative)

All requirements-classes and conformance-classes described in this document are owned by the standard(s) identified.
